# Generated by Django 3.1.1 on 2020-10-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cargo',
            field=models.CharField(choices=[('1', 'Supervisor'), ('2', 'Administrador'), ('3', 'Atendente')], max_length=20, verbose_name='cargo'),
        ),
    ]
