# Generated by Django 3.1.1 on 2020-11-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201013_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ramal',
            field=models.CharField(default=200, max_length=30, verbose_name='Agente'),
            preserve_default=False,
        ),
    ]
