# Generated by Django 3.1.1 on 2021-01-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cargo',
            field=models.ManyToManyField(to='users.Cargo'),
        ),
    ]
