# Generated by Django 3.1.1 on 2021-01-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='carga_horaria',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cargo',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
