# Generated by Django 3.1.1 on 2021-01-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210121_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cargo',
        ),
        migrations.AddField(
            model_name='profile',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.cargo'),
            preserve_default=False,
        ),
    ]
