# Generated by Django 3.1.1 on 2021-01-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210121_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agencia',
            field=models.IntegerField(default=1, verbose_name='Agência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='banco',
            field=models.CharField(default=1, max_length=30, verbose_name='Banco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='conta',
            field=models.IntegerField(default=1, verbose_name='Conta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.IntegerField(default=1, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='endereco',
            field=models.CharField(default=1, max_length=250, verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
