# Generated by Django 3.1.1 on 2021-01-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210127_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Foto'),
        ),
    ]
