# Generated by Django 3.1.1 on 2021-01-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(null=True, upload_to='static/images/', verbose_name='Foto'),
        ),
    ]
