# Generated by Django 3.1.1 on 2021-02-22 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_auto_20210128_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agencia',
            field=models.IntegerField(blank=True, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='banco',
            field=models.CharField(blank=True, max_length=30, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cargo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='users.cargo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='conta',
            field=models.IntegerField(blank=True, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.IntegerField(blank=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='endereco',
            field=models.CharField(blank=True, max_length=250, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ramal',
            field=models.CharField(blank=True, max_length=30, verbose_name='Agente'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
