# Generated by Django 3.2.2 on 2021-07-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20210509_2346'),
        ('users', '0014_profile_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='tasks.empresas'),
        ),
    ]
