# Generated by Django 3.2.2 on 2021-06-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento_model', to='events.imagealbum'),
        ),
    ]
