# Generated by Django 3.2.2 on 2021-06-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resposta_model', to='events.imagealbum'),
        ),
    ]
