# Generated by Django 3.2.2 on 2021-06-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_resposta_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='evento',
        ),
        migrations.AddField(
            model_name='event',
            name='resposta',
            field=models.ManyToManyField(blank=True, null=True, related_name='resposta_event', to='events.Resposta'),
        ),
    ]
