# Generated by Django 3.2.2 on 2021-06-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210624_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='resposta',
            field=models.ManyToManyField(blank=True, related_name='resposta_event', to='events.Resposta'),
        ),
    ]
