# Generated by Django 3.2.2 on 2021-06-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cpf',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPF Cliente'),
        ),
        migrations.AlterField(
            model_name='event',
            name='data_relato',
            field=models.DateField(blank=True, null=True, verbose_name='Data Relato'),
        ),
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.imagealbum'),
        ),
    ]
