# Generated by Django 3.2.2 on 2021-06-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_imagealbum_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parecer_cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parecer Cliente'),
        ),
        migrations.AddField(
            model_name='event',
            name='parecer_core',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parecer Core'),
        ),
        migrations.AddField(
            model_name='event',
            name='status_cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Cliente'),
        ),
        migrations.AddField(
            model_name='event',
            name='status_core',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Core'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
