# Generated by Django 3.1.1 on 2020-12-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=90, null=True, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('cpf', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPF')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=50, null=True, verbose_name='CEP')),
                ('slug', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
