# Generated by Django 3.0.8 on 2020-08-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contract_pack', models.IntegerField()),
                ('contract_value', models.IntegerField()),
                ('cnpj', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=60)),
                ('start_data', models.DateField()),
                ('end_contract', models.DateField()),
                ('service_level', models.IntegerField()),
                ('excedent', models.IntegerField()),
                ('it_respon', models.CharField(max_length=60)),
            ],
        ),
    ]
