# Generated by Django 3.0.8 on 2020-08-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_chamadas_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='excedent',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
