# Generated by Django 3.0.8 on 2020-08-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200828_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='protocolo',
            new_name='u_id',
        ),
        migrations.AlterField(
            model_name='empresas',
            name='excedent',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='service_level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=1),
        ),
    ]
