# Generated by Django 3.0.8 on 2020-09-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200831_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='protocolo',
            field=models.CharField(default=20200831, max_length=30),
            preserve_default=False,
        ),
    ]
