# Generated by Django 3.1.1 on 2020-10-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tickets_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='cnpj',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='contract_pack',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='contract_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='end_contract',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='excedent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='it_respon',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='owner',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='service_level',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='start_data',
            field=models.DateField(blank=True),
        ),
    ]
