# Generated by Django 3.1.1 on 2020-10-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20201013_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='contract_pack',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='contract_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='excedent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
