# Generated by Django 3.1.1 on 2020-11-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20201015_1350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
