# Generated by Django 3.1.1 on 2021-05-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_delete_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='last_renew',
            field=models.DateField(blank=True, null=True, verbose_name='Ultima Renovação'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cnpj',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='contract_pack',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pacote Atendimentos'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='contract_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Valor Pacote'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='end_contract',
            field=models.DateField(blank=True, null=True, verbose_name='Fim contrato'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='owner',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Responsanvel'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='start_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data Entrada'),
        ),
    ]
