# Generated by Django 3.1.1 on 2021-05-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20210509_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='cidade',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='endereco',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='estado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado'),
        ),
    ]
