# Generated by Django 3.1.1 on 2021-05-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20210509_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='cidade',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='endereco',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nome'),
        ),
    ]
