# Generated by Django 3.1.1 on 2020-12-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoSlugTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo')),
                ('assunto', models.CharField(blank=True, max_length=30, null=True, verbose_name='Assunto')),
                ('data_abertura', models.DateTimeField()),
                ('cliente', models.CharField(blank=True, max_length=30, null=True)),
                ('responsavel', models.CharField(max_length=30)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('service', models.CharField(blank=True, max_length=30, null=True)),
                ('descri', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
                ('protocolo', models.CharField(blank=True, max_length=30, null=True)),
                ('empresa', models.CharField(default='Core', max_length=100)),
                ('id_ligacao', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SlugTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_atendimento', models.TimeField(blank=True, null=True, verbose_name='Tempo Atendimento')),
                ('tempo_espera', models.TimeField(blank=True, null=True, verbose_name='Tempo Espera')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_termino', models.DateTimeField(blank=True, null=True, verbose_name='Data Final')),
                ('responsavel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Resposavel')),
                ('cliente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cliente')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('empresa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Empresa')),
                ('id_ligacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Ligação')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Ligação')),
                ('slug', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
