# Generated by Django 3.1.1 on 2020-12-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20201206_2116'),
        ('vueshow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noslugtest',
            name='teste_model',
            field=models.ManyToManyField(to='tickets.Tickets'),
        ),
        migrations.AddField(
            model_name='slugtest',
            name='teste_model',
            field=models.ManyToManyField(to='tickets.Tickets'),
        ),
    ]
