# Generated by Django 3.0.8 on 2020-09-01 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('assunto', models.CharField(max_length=30)),
                ('data_abertura', models.DateField()),
                ('cliente', models.CharField(max_length=30)),
                ('responsavel', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('service', models.CharField(max_length=30)),
                ('descri', models.CharField(max_length=500)),
                ('protocolo', models.CharField(max_length=30)),
            ],
        ),
    ]
