# Generated by Django 3.1.1 on 2020-09-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='choicing',
            field=models.CharField(choices=[('Wimax', 'Wimax'), ('R2 Telecom', 'R2 Telecom')], default='Core', max_length=100),
        ),
    ]
