# Generated by Django 3.1.1 on 2020-09-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_tickets_choicing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='choicing',
            field=models.CharField(choices=[('Wimax', 'Wimax'), ('R2 Telecom', 'R2 Telecom'), ('Telecall', 'Telecall'), ('Proxer', 'Proxer'), ('Cambuhy', 'Cambuhy'), ('Sothis', 'Sothis')], default='Sothis', max_length=100),
        ),
    ]
