# Generated by Django 3.1.1 on 2020-10-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20201013_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='empresa',
            field=models.CharField(choices=[], default='Core', max_length=100),
        ),
    ]
