# Generated by Django 3.1.1 on 2020-10-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20201013_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='id_ligação',
            new_name='id_ligacao',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='assunto',
            field=models.CharField(blank=True, choices=[('1', 'IMPRODUTIVA'), ('2', 'SUPORTE'), ('3', 'COMERCIAL'), ('4', 'FINANCEIRO'), ('5', 'FUTURO CLIENTE'), ('6', 'NÃO REGISTRADO'), ('7', 'RECHAMADA')], max_length=30, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='empresa',
            field=models.CharField(choices=[(1, 'Wimax'), (2, 'Proxer'), (3, 'Telecall'), (4, 'R2 Telecom'), (5, 'RVT'), (6, 'Cambuhy')], default='Core', max_length=100),
        ),
    ]
