# Generated by Django 3.1.1 on 2020-11-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20201015_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='assunto',
            field=models.CharField(blank=True, choices=[('1', 'IMPRODUTIVA'), ('2', 'SUPORTE'), ('3', 'COMERCIAL'), ('4', 'FINANCEIRO'), ('5', 'FUTURO CLIENTE'), ('6', 'NÃO REGISTRADO'), ('7', 'RECHAMADA'), ('8', 'Teste')], max_length=30, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='empresa',
            field=models.CharField(default='Core', max_length=100),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='protocolo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='service',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
