# Generated by Django 3.1.1 on 2020-11-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20201124_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ligacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_atendimento', models.TimeField(blank=True, null=True, verbose_name='Tempo Atendimento')),
                ('tempo_espera', models.TimeField(blank=True, null=True, verbose_name='Tempo Espera')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data Inicio')),
                ('data_termino', models.DateTimeField(blank=True, null=True, verbose_name='Data Final')),
                ('responsavel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Resposavel')),
                ('cliente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cliente')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('empresa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Empresa')),
                ('id_ligacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Ligação')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link Ligação')),
            ],
        ),
    ]
