# Generated by Django 3.1.1 on 2020-12-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ligacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='slug',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='assunto',
            field=models.CharField(blank=True, choices=[('1', 'IMPRODUTIVA'), ('2', 'SUPORTE'), ('3', 'COMERCIAL'), ('4', 'FINANCEIRO'), ('5', 'FUTURO CLIENTE'), ('6', 'NÃO REGISTRADO'), ('7', 'RECHAMADA')], max_length=30, null=True, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='service',
            field=models.CharField(blank=True, default='Telefonico', max_length=30, null=True, verbose_name='Serviço'),
        ),
    ]
