# Generated by Django 3.1.1 on 2020-12-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20201206_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligacoes',
            name='ticket',
            field=models.ManyToManyField(to='tickets.Tickets'),
        ),
    ]
