# Generated by Django 3.1.1 on 2020-12-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_delete_tickets'),
        ('tickets', '0012_ligacoes_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligacoes',
            name='ticket',
            field=models.ManyToManyField(to='tasks.Empresas'),
        ),
    ]
