# Generated by Django 3.1.1 on 2020-12-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20201214_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligacoes',
            name='ticket',
        ),
    ]
