# Generated by Django 3.1.1 on 2021-01-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_remove_ligacoes_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='service',
            field=models.CharField(blank=True, choices=[('1', 'Telefonico'), ('2', 'Whatsapp'), ('3', 'Telefonico Retorno'), ('4', 'Whatsapp Retorno')], default='Telefonico', max_length=30, null=True, verbose_name='Serviço'),
        ),
    ]
