# Generated by Django 3.1.1 on 2021-01-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20210107_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='status',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='slug',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
