# Generated by Django 3.1.1 on 2021-01-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20210108_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='assunto',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Assunto'),
        ),
    ]
