# Generated by Django 3.1.1 on 2021-04-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20210120_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='prot_sistema',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
