# Generated by Django 3.1.1 on 2021-04-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_tickets_prot_sistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='prot_sistema',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Protocolo Sistema'),
        ),
    ]
