# Generated by Django 3.1.1 on 2021-04-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_auto_20210411_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='descri',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Descrição'),
        ),
    ]
