# Generated by Django 3.1.1 on 2020-09-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contract_pack', models.IntegerField()),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cnpj', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=60)),
                ('start_data', models.DateField()),
                ('end_contract', models.DateField()),
                ('service_level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=1)),
                ('excedent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('it_respon', models.CharField(max_length=60)),
            ],
        ),
    ]
